DATA:
  data_sampler: weighted
  dataset_path: datasets/data/MSRAction3D_fps
  frame_skip: 1
  frames_per_clip: 64
  gender: all
  n_points: 128
  name: MSR-Action3D
  noisy_data:
    test: false
    train: false
  shuffle_points: fps_each_frame
MODEL:
  3DMFV:
    n_gaussians: 8
  P4TRANSFORMER:
    depth: 10
    dim: 1024
    dim_head: 256
    dropout1: 0.05
    dropout2: 0.5
    emb_relu: false
    heads: 8
    mlp_dim: 2048
    nsamples: 32
    radius: 0.1
    spatial_stride: 32
    temporal_kernel_size: 3
    temporal_stride: 2
  PSTNET:
    nsamples: 9
    radius: 0.1
  PST_TRANSFORMER:
    depth: 5
    dim: 1024
    dim_head: 256
    dropout1: 0.0
    dropout2: 0.5
    heads: 8
    mlp_dim: 2048
    nsamples: 32
    radius: 0.1
    spatial_stride: 32
    temporal_kernel_size: 3
    temporal_stride: 2
  SET_TRANSFORMER:
    dim_hidden: 512
    dim_input: 3
    ln: false
    num_heads: 4
    num_inds: 32
    num_outputs: 1
    temporal_smoothing: 0
  TPATCHES:
    attn_num_heads: 4
    centroid_jitter: 0.005
    downsample_method: fps
    extractor_type: strided
    k:
    - 16
    - 16
    - 16
    local_temp_convs:
    - 7
    - 3
    - 3
    npoints:
    - 512
    - 128
    - null
    radius:
    - 0.2
    - 0.4
    - null
    sample_mode: nn
    temp_conv: 64
    temporal_stride: 1
    type: skip_con
  pc_model: set_transformer
TESTING:
  aug:
  - ''
  batch_size: 2
  set: test
TRAINING:
  aug:
  - ''
  batch_size: 32
  lr: 0.001
  n_epochs: 3000
  pretrained_model: null
  refine: true
  refine_epoch: 2700
  steps_per_update: 8
num_workers: 0
save_every: 10
seed: 0
