seed: 0
save_every: 10
num_workers: 0

MODEL:
  pc_model: 'pst_transformer' # which model to use for point cloud processing
  3DMFV:
    n_gaussians: 8
  SET_TRANSFORMER:
    dim_input: 3
    num_outputs: 1
    num_inds: 32
    dim_hidden: 512
    num_heads: 4
    ln: False
    temporal_smoothing: 0
  PATCHLET:
    centroid_jitter: 0.005
    sample_mode: 'nn'  # nn | randn | gt type of patchlet sampling
    k: [ 16, 16, 16 ]
    npoints: [ 512, 128, null ]
    temp_conv: 7
    downsample_method: 'fps'
    radius: [0.2, 0.4, null]
    type: 'skip_con' # 'origin' / 'skip_con' / 'attn_last_layer' / 'attn_all_layers'
    attn_num_heads: 4 # only applicable with 'attn_last_layer' or 'attn_all_layers'
    bidirectional: True # True | False to use bidirectional t-patches
  PSTNET:
    radius: 0.1
    nsamples: 9
  PST_TRANSFORMER:
    radius: 0.3
    nsamples: 32
    spatial_stride: 32
    temporal_kernel_size: 3
    temporal_stride: 2
    dim: 80
    depth: 5
    heads: 2
    dim_head: 40
    dropout1: 0.0
    mlp_dim: 160
    dropout2: 0.0

TRAINING:
  lr: 0.001
  steps_per_update: 8
  batch_size: 2
  n_epochs: 200
  refine: False
  refine_epoch: 0
  pretrained_model: null
  aug: [''] # 'scale', 'translate'

TESTING:
  batch_size: 2
  aug: ['']
  set: 'test'

DATA:
  name: 'DFAUST'
  dataset_path: '/home/sitzikbs/Datasets/dfaust/'
  frames_per_clip: 64
  frame_skip: 1
  n_points: 1024
  shuffle_points: 'fps_each_frame' # 'each | none | fps_each_frame| fps_each'
  gender: 'all'
  data_sampler: 'weighted'
  noisy_data:
    train: False
    test: False
