MODEL:
  pc_model: 'pn2' # which model to use for point cloud processing
  3DMFV:
    n_gaussians: 8
  PATCHLET:
    centroid_jitter: 0.005
    sample_mode: 'nn'  # nn | randn | mean type of patchlet sampling
    k: 16
    downsample_method: 'fps'

TRAINING:
  lr: 0.001
  steps_per_update: 1
  batch_size: 1
  n_epochs: 1
  refine: False
  refine_epoch: 0
  pretrained_model: null

TESTING:
  batch_size: 2


DATA:
  dataset_path: '/home/sitzikbs/Datasets/ikeaego_small_clips/32/'
  frame_skip: 1
  n_points: 1024