MODEL:
  pc_model: 'pn1_4d_basic' # which model to use for point cloud processing
  3DMFV:
    n_gaussians: 8
  PATCHLET:
    patchlet_centroid_jitter: 0.005
    patchlet_sample_mode: 'nn'  # nn | randn | gt type of patchlet sampling
    k: 16
    downsample_method: 'fps'

TRAINING:
  lr: 0.001
  steps_per_update: 1
  batch_size: 8
  n_epochs: 200
  refine: False
  refine_epoch: 0
  pretrained_model: null
  aug: ['']

TESTING:
  batch_size: 2
  aug: ['']
  set: 'test'

DATA:
  dataset_path: '/home/shrout/Data_sets/dfaust/'
  frames_per_clip: 32
  frame_skip: 1
  n_points: 1024
  shuffle_points: 'fps_each_frame' # 'each | none | fps_each_frame| fps_each'
  gender: 'all'
  data_sampler: 'weighted'
